// generated by scripts/build-icons.js
export default {
  "olc-state": "data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%222048mm%22%20height%3D%222048mm%22%20viewBox%3D%220%200%202048%202048%22%3E%3Crect%20width%3D%221648%22%20height%3D%22900%22%20x%3D%22187.67%22%20y%3D%22-1433.358%22%20ry%3D%22200%22%20style%3D%22fill%3Anone%3Bstroke%3A%23000%3Bstroke-width%3A99.9998%22%20transform%3D%22translate(12.33%202007.358)%22%2F%3E%3C%2Fsvg%3E"
};
